# Generated by Django 4.1.7 on 2023-03-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionType', models.CharField(blank=True, max_length=200)),
                ('transID', models.CharField(blank=True, max_length=200)),
                ('transTime', models.CharField(blank=True, max_length=200)),
                ('transAmount', models.CharField(blank=True, max_length=200)),
                ('businessShortCode', models.CharField(blank=True, max_length=200)),
                ('billRefNumber', models.CharField(blank=True, max_length=200)),
                ('invoiceNumber', models.CharField(blank=True, max_length=200)),
                ('orgAccountBalance', models.CharField(blank=True, max_length=200)),
                ('thirdPartyTransID', models.CharField(blank=True, max_length=200)),
                ('mSISDN', models.CharField(blank=True, max_length=200)),
                ('firstName', models.CharField(blank=True, max_length=200)),
                ('middleName', models.CharField(blank=True, max_length=200)),
                ('lastName', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
