# Generated by Django 4.1.7 on 2023-03-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LNMTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckoutRequestID', models.CharField(blank=True, max_length=200)),
                ('ResultCode', models.CharField(blank=True, max_length=200)),
                ('ResultDesc', models.CharField(blank=True, max_length=200)),
                ('merchantRequestID', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='MpesaTransaction',
            new_name='C2BMpesaTransaction',
        ),
    ]
