# Generated by Django 4.1.7 on 2023-03-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_lnmtransactions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lnmtransactions',
            old_name='CheckoutRequestID',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='lnmtransactions',
            old_name='ResultCode',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='lnmtransactions',
            old_name='ResultDesc',
            new_name='checkoutRequestID',
        ),
        migrations.AddField(
            model_name='lnmtransactions',
            name='mpesaReceiptNumber',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lnmtransactions',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lnmtransactions',
            name='resultCode',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lnmtransactions',
            name='resultDesc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lnmtransactions',
            name='transactionDate',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
