# Generated by Django 4.1.7 on 2023-03-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_rename_checkoutrequestid_lnmtransactions_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lnmtransactions',
            name='target_account',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
